name: Build & Release EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build EXE using Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/src/ cdrx/pyinstaller-windows:python3@sha256:7d7bcb510a2e785f4936a2a61989fa93ff1eeba3b80571fbba919c23e52a0a63 

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: barcode_rename
          path: dist/windows/barcode_rename/barcode_rename.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: barcode_rename

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body_path: README.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .dist/windows/barcode_rename/barcode_rename.zip
          asset_name: barcode_rename.zip
          asset_content_type: application/zip