name: Build & Release EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build EXE using Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/src/ cdrx/pyinstaller-windows:python3@sha256:7d7bcb510a2e785f4936a2a61989fa93ff1eeba3b80571fbba919c23e52a0a63 

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: barcode_rename
          path: dist/windows/barcode_rename/barcode_rename.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: barcode_rename

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/windows/barcode_rename/barcode_rename.exe
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}